// @here we will set up our action types
// @for example
export const LOGIN = 'LOGIN';
export const GET_ALL_ARTICLE = 'GET_ALL_ARTICLE';
export const SEND_LINK_SUCCESS = 'SEND_LINK_SUCCESS';
export const SEND_LINK_FAIL = 'SEND_LINK_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const SUBMIT_SIGNUP_FORM = 'SUBMIT_SIGNUP_FORM';
export const SET_SUBMIT_USERS = 'SET_SUBMIT_USERS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const LOADING_ON_SUBMIT = 'LOADING_ON_SUBMIT';
export const CLOSE_POPUP_ON_SUCCESS = 'CLOSE_POPUP_ON_SUCCESS';
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_FAILURE = 'SOCIAL_LOGIN_FAILURE';
